---
title: "Which people are most affected by changes to data linkage methodology?"
subtitle: "An exploration of patient, organisational and spatiotemporal characteristics in administrative hospital data in England"
author: "Tony Stone, UCL / University of Sheffield"
date: 2023-11-16
date-format: "D MMM YYYY"
format: 
  revealjs:
    logo: imgs/logo.png
    theme: solarized
bibliography: adruk-conf.bib
csl: vancouver.csl
nocite: |
  @*
css: styles.css
---

## Context {.smaller}

+ NHS England (née Digital) operate various data services/collections for/from 
organisations receiving funds from the NHS in England
+ In 2021 NHS Digital changed how they assign records to an _individual_ within 
their hospital episode statistics (HES) datasets, the first change in 12 years
+ HES is a very widely used administrative health data collection in England, 
by
    + Providers
    + Commissioners
    + Researchers (inc. within the UK's national statistics institute)

::: {.notes}
Slide notes
:::

## What are the HES datasets {.smaller}

+ event based records at the patient-activity level
+ for specific types of care provision
+ funded by the English NHS -OR- taking place in a NHS hospital in England.

:::: {.columns}
::: {.column width="33%" .col-no-border}

### Admitted patient care (APC)

+ Admitted to hospital (inc. day case admissions)
+ Since 1989 but NHS Number only mandated since 1997
+ Additional HES Critical Care (CC) dataset available

:::
::: {.column width="33%" .col-left-border}

### Outpatient (OP) appointments

+ Attended and unattended
+ Since 2003

:::
::: {.column width="33%" .col-left-border}

### Accident and Emergency (A&E)

+ Non-admitted unscheduled(-ish) care at
    + Emergency Departments
    + Urgent Care Centres
    + Minor Injury Units
    + Walk-in Centres
+ From 2007 to 2020

:::
::::

## Data submitted used to identify patients within HES {.smaller}

+ NHS Number
+ Date of birth
+ Stated gender (though named `sex` and likely to have changed over time)
+ Postcode of patient place of residence
+ Local patient identifier
+ Local patient identifier provider (NHS Trust)

### What's not available

+ Names
+ Address precision better than postcode
    + 15 properties, but up to 100, per postcode.

## HES ID algorithm {background-color="#d1ffbd"}

:::: {.columns}
::: {.column width="70%"}

+ deterministic
+ stepwise
+ __clusters__ HES records into disjoint sets

:::

::: {.column width="30%"}

```{dot}
//| fig-width: 3

graph {
  rankdir="LR";
  node[shape="point", labelloc=c, labeljust=r]
  fontname = "Helvetica,Arial,sans-serif";
  bgcolor = "transparent";
  
  subgraph cluster_all {
    style="rounded"
    label="HES records"
    
  subgraph cluster_pid1 {
    style="rounded"
    label="HES ID 1"
    bgcolor="#1b9e77"
    a1
    a2
  }
  
  subgraph cluster_pid2 {
    style="rounded"
    label="HES ID 2"
    bgcolor="#d95f02"
    a3
  }
  
  subgraph cluster_pid3 {
    style="rounded"
    label="HES ID 3"
    bgcolor="#7570b3"
    a4
    a5
  }
  }
}
```

:::
::::


## Person ID assignment algorithm (MPS) {background-color="#c5eafa"}

### MPS: Master Patient Service

:::: {.columns}
::: {.column width="70%"}

Used across NHS Digital/England's "directed" data collections.

+ deterministic
+ stepwise
+ based on data available at the point of algorithm execution
+ __Links__ each HES record to - at most - one identity

:::

::: {.column width="30%"}

```{dot}
//| fig-width: 3

digraph {
  rankdir="LR";
  node[shape="point", labelloc=c, labeljust=l]
  fontname = "Helvetica,Arial,sans-serif";
  bgcolor = "transparent";
    
  subgraph cluster_records {
    style="rounded"
    label="HES records"
    labeljust=l
    a1
    a2
    a3
    a4
    a5
    a6 [style="invis"]
  }
  
  subgraph cluster_persons {
    style="rounded"
    label="Person IDs"
    b1 [xlabel="A"]
    b2 [xlabel="B"]
    b3 [xlabel="C"]
    b4 [style="invis"]
  }
  
  a1->b1
  a2->b1
  a3->b2
  a4->b3
  a5->b3
}
```

:::
::::


## Data source

+ HES datasets
+ April 2007 - March 2020 (13 years)
+ Patients aged 55 or less at date of activity (i.e. must have date of birth)

Amounts to:

+ 979 million records
+ 59 million distinct HES IDs
+ 55 million distinct Person IDs
+ 60 million distinct (HES ID, Person ID)-pairs

## Uninformative, Simple, Merges, Splits and the Complex

:::: {.columns}
::: {.column width="60%"}

| categorisation | records | distinct pairs | HES IDs | Person IDs |
|----------------|--------:|---------------:|--------:|-----------:|
| "Uninformative"| 9.3M    | -              | -       | -          |
| Simple         | 881.3M  | 42.1M          | -       | -          |
| Merge (HES ID) | 69.0M   | 6.5M           | -       | 2.5M       |
| Split (HES ID) | 13.2M   | 1.1M           | 0.4M    | -          |
| Complex        | 6.6M    | 0.6M           | 0.4M    | 0.4M       |

:::
::: {.column width="40%"}
```{dot}
//| fig-width: 4

graph {
rankdir="LR";
labeljust=l
labelloc = t;
fontname = "Helvetica,Arial,sans-serif";
bgcolor = "transparent";
node [shape = oval, style = filled, labeljust=c, fillcolor = "#d1ffbd"];


subgraph cluster_complex {
label="Complex"

{rank=same
h6 h7
}

{rank=same
p6 p7
}

h6 [label = "HES ID: 1"]
h7 [label = "HES ID: 2"]
p6 [label = "Person ID: A", fillcolor = "#c5eafa"]
p7 [label = "Person ID: B", fillcolor = "#c5eafa"]

h6 -- {p6 p7}
h7 -- p7
}


subgraph cluster_split {
label="Split"

h5 [label = "HES ID: 1"]
p4 [label = "Person ID: A", fillcolor = "#c5eafa"]
p5 [label = "Person ID: B", fillcolor = "#c5eafa"]

{rank=same
p4 p5
}

h5 -- {p4 p5}
}


subgraph cluster_merge {
label="Merge"

h3 [label = "HES ID: 1"]
h4 [label = "HES ID: 2"]
p3 [label = "Person ID: A", fillcolor = "#c5eafa"]

{rank=same
h3 h4
}

{h3 h4} -- p3
}

subgraph cluster_simple {
label="Simple"

h2 [label = "HES ID: 1"]
p2 [label = "Person ID: A", fillcolor = "#c5eafa"]

h2 -- p2
h2 -- p2
}



subgraph cluster_uninformative {
label="\"Uninformative\""

h1 [label = "HES ID: 1"]
p1 [label = "Person ID: A", fillcolor = "#c5eafa"]

h1 -- p1;
}

}
```

:::
::::

## Features investgated

First reported:
+ Age (grouped: Infants, Children, Young Adults, Adults)
+ Gender
+ Ethnicity
+ Index of deprivation quintile
+ Year of activity

And:
+ Total activity records (grouped into quintiles)

## Results

```{r}
library(data.table)
library(ggplot2)


regression_results <- readRDS("data/regression_results.rds")

regression_results[, ':=' (est = exp(est_log),
                           est_low95 = exp(est_log - qnorm(0.975)*est_se_log),
                           est_high95 = exp(est_log + qnorm(0.975)*est_se_log))]


dodger = position_dodge(width = 0.5)

ggplot(regression_results, aes(y = est, x = param, colour = model)) +
  geom_pointrange(aes(ymin = est_low95, ymax = est_high95),
                  position = dodger) +
    scale_x_discrete(limits=rev) +
  geom_hline(yintercept = 1.0, color = "blue") +
  scale_y_log10(breaks = c(0.2, 0.5, 1.0, 2.0, 5.0),
                minor_breaks = NULL) +
  scale_color_brewer(palette = "Dark2") +
  labs(y = "Odds ratio (logarithmic scale)", x = NULL) +
  coord_flip(ylim = c(0.1, 10)) +
  theme_minimal()

```

## Disscussion

+ Changes act at the fringes (91% records unchanged)
+ Most group wise differences are small
+ Greatest differences likely due to:
    + location information (as key component in linkage)
    + improved data recording / verification by Trusts
+ Deprivation still a factor
+ Reason for activity not investigated in this work

## Acknowledgements {.smaller}

We gratefully acknowledge all the patients whose de-identified data 
are used in this research.  

This work uses data provided by patients and collected by the National Health 
Service as part of their care and support. Source data can also be accessed by 
researchers by applying to NHS England.

This work is/was supported by ADR UK (Administrative Data Research UK), an 
Economic and Social Research Council (part of UK Research and Innovation) 
programme.

This research benefits from and contributes to the NIHR Children and Families 
Policy Research Unit, but was not commissioned by the National Institute for 
Health Research (NIHR) Policy Research Programme. The views expressed are 
those of the author(s) and not necessarily those of the NIHR or the Department 
of Health and Social Care. 


## References {.smaller}

::: {#refs}
:::
